# Pretraining checkpoint path
init_checkpoint: "logs/run_id/state_step_100000.pt"
# Instruct SFT training configuration
train_files: "data/instruct_mix/instruct_train_*.bin"
val_files: "data/instruct_mix/instruct_val_*.bin"
train_seq_len: 64*1024
val_seq_len: 64*1024
num_iterations: 400
cooldown_frac: 0.9

# Common settings
vocab_size: 50257
val_tokens: 10485760
val_loss_every: 125
save_checkpoint: true