# Instruct SFT training configuration
train_files: "data/instruct_mix/instruct_train_*.bin"
val_files: "data/instruct_mix/instruct_val_*.bin"
train_seq_len: 2048
val_seq_len: 8192
num_iterations: 3000
cooldown_frac: 0.9

# Common settings
vocab_size: 50257
val_tokens: 10485760
val_loss_every: 125
save_checkpoint: true