# Pretraining configuration
train_files: "data/fineweb100B/fineweb_train_*.bin"
val_files: "data/fineweb100B/fineweb_val_*.bin"
train_seq_len: 65536      # 64 * 1024
val_seq_len: 262144       # 4 * 64 * 1024
num_iterations: 5960
cooldown_frac: 0.7

# Common settings
vocab_size: 50257
val_tokens: 10485760
val_loss_every: 125
save_checkpoint: true